version: '3.1'

services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Security_or_no

  app:
    container_name: spring-boot-app
    image: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
          
  